spring:
  thymeleaf:
    cache: false

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/javaweb_exam?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

  # 编码格式
  http:
    encoding:
      force: true
      enabled: true
      charset: utf-8

  # 上传文件大小
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB


server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
